spring:
  output.ansi.enabled: ALWAYS

  datasource:
    url: jdbc:mysql://localhost:3306/security
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate.ddl-auto: update #create update none
    properties.hibernate.format_sql: true
    naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    cache: false
